### ISSUE TITLE
Azure Auth: http://localhost:5000/?error=server_error&error_description=Error+getting+user+email+from+external+provider

### ISSUE THREAD

**Issue by mike-hogan** [supabase/gotrue#550] opened 2021-12-28 12:02 UTC
# Bug report

## To Reproduce

1. Register a new app registration in azure portal, giving access to organisations and personal accounts
2.  Register the supabase redirect uri as a "Web" redirect uri (in azure portal)
3. Create a secret for this new app registration
4. enable azure auth in supabase, pasting in the client id and secret of the new app registration
5. Invoke:

```
const {user, session, error} = await supabase.auth.signIn({
            provider: 'azure',
        })
```

6. That calls https://rlgaaitetwbkhisssmkq.supabase.co/auth/v1/authorize?provider=azure
7. Which returns with a 302 to https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=16d4a427-b73c-45fc-b04f-9545e7273f21&redirect_uri=https://rlgaaitetwbkhisssmkq.supabase.co/auth/v1/callback&response_type=code&scope=openid&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJle.......
8. Which returns with a 200 and pops the Microsoft Auth dialog, asking for me to grant permission to the app.  Note, it does not ask me what Microsoft identity to use, I assume its using the identity I am using to log into Azure Portal.
9. I grant permission, then it seems to load https://login.live.com/Me.htm?v=3
10. Then it seems to load https://login.live.com/oauth20_authorize.srf?client_id=16d4a427-b73c-45fc-b04f-9545e7273f21&scope=openid&redirect_uri=https://rlgaaitetwbkhisssmkq.supabase.co/auth/v1/callback&response_type=code&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ....&uaid=95c5d4c9a43f406ca88c5b1b22ea432a&msproxy=1&issuer=mso&tenant=common&ui_locales=en-GB
11. Then it loads https://account.live.com/Consent/Update?mkt=EN-GB&uiflavor=web&id=293577&ru=https://login.live.com/oauth20_authorize.srf?uaid=95c5d4c9a43f406ca88c5b1b22ea432a&opid=A353DB724539E16F&opidt=1640691597
12. Eventually we get to https://login.live.com/oauth20_authorize.srf?uaid=95c5d4c9a43f406ca88c5b1b22ea432a&opid=A353DB724539E16F&opidt=1640691597&res=success&route=R3_BAY
13. which returns a 302 to https://rlgaaitetwbkhisssmkq.supabase.co/auth/v1/callback?code=M.R3_BAY.f96be895-105c-c9f1-5462-d0b31af76746&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey....
14. Invoking https://rlgaaitetwbkhisssmkq.supabase.co/auth/v1/callback?code=M.R3_BAY.f96be895-105c-c9f1-5462-d0b31af76746&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey... returns a 302 to http://localhost:5000/?error=server_error&error_description=Error+getting+user+email+from+external+provider

## Expected behavior

I have done the same steps for Google Auth, and it worked, expect the same to happen for Azure auth.

Also, I have successfully logged in using Azure using similar steps using the Microsoft Native javascript sdk for auth, @azure/msal-browser

I am aware of https://github.com/supabase/gotrue/pull/54 , but two things on that.  The first is: I was not presented with an option to select an email address to login with (presumably because I am already logged into azure portal?) but even if I was, the second point is that I don't expect my customers to login using this weird azure specific email address.  I expect them to login using their "usual" azure identity.

**Comment by CodeCakePie** [comment] 2022-09-15 12:49
I also have this issue

**Comment by plondon** [comment] 2022-11-01 20:40
I was able to fix this by using `common` instead of the `tenant_id` as suggested by the docs.

https://login.microsoftonline.com/common

**Comment by kaleabmelkie** [comment] 2022-11-18 09:56
Although unrelated to Azure, there is a similar issue for the Keycloak integration which I've fixed by adding `openid` in the scopes option.

```ts
async function signInWithKeycloak() {
  const { user, session, error } = await supabase.auth.signIn(
    {provider: 'Keycloak'},
    {scopes: 'openid'}
  )
}
```

It should probably get documented in [this integration guide](https://supabase.com/docs/guides/auth/auth-keycloak).

**Comment by anthonylaflamme** [comment] 2023-06-07 19:37
I have the same issue right now any way to solve this ? 

Error:  

`/SignIn?error=server_error&error_description=Error+getting+user+email+from+external+provider`

My signInWithOAuth returns this error

Here is my oauth call:

    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: 'azure',
      options: {
        scopes: 'email',
        redirectTo: 'nativeAddress//--/SignIn',
      },
    })
The redirect is fine, anyways it doesn't even get there it fails on the returned data url
I followed the supabase social login docs and made sure all api permissions were on

<img width="1017" alt="Screenshot 2023-06-07 at 3 35 30 PM" src="https://github.com/supabase/gotrue/assets/4626172/14dfd564-46bf-4599-9cdf-491af2365fda">

**Comment by hf** [comment] 2023-06-07 19:39
Hey so there was a report that on some Azure accounts the email is encoded differently. @silentworks do you recall?

**Comment by hf** [comment] 2023-06-08 12:36
@anthonylaflamme We have a theory that the problem is #1130 but have no way of testing. Do you mind contacting support@supabase.com and link to this comment so we can discuss if we can find a way to test this with you?

**Comment by silentworks** [comment] 2023-06-12 00:55
@anthonylaflamme Yes a support ticket on the dashboard would work too. Just mention this issue in that ticket so we know it's you.

**Comment by karan2801** [comment] 2023-09-01 04:23
@anthonylaflamme Were you able to figure out a solution for this with the Supabase team?

**Comment by anthonylaflamme** [comment] 2023-09-01 15:45
@karan2801 wasn't able to test got assigned another task at my workplace. I know i'm coming back on this in about a month. Although I was using a personal free account for test so I don't know if that is why it was causing issue.

**Comment by madil4** [comment] 2023-09-14 12:56
@

> I have the same issue right now any way to solve this ?
> 
> Error:
> 
> `/SignIn?error=server_error&error_description=Error+getting+user+email+from+external+provider`
> 
> My signInWithOAuth returns this error
> 
> Here is my oauth call:
> 
> ```
> const { data, error } = await supabase.auth.signInWithOAuth({
>   provider: 'azure',
>   options: {
>     scopes: 'email',
>     redirectTo: 'nativeAddress//--/SignIn',
>   },
> })
> ```
> 
> The redirect is fine, anyways it doesn't even get there it fails on the returned data url I followed the supabase social login docs and made sure all api permissions were on
> 
> <img alt="Screenshot 2023-06-07 at 3 35 30 PM" width="1017" src="https://user-images.githubusercontent.com/4626172/244177833-14dfd564-46bf-4599-9cdf-491af2365fda.png">

I'm facing the same issue, any solution so far?

**Comment by Freez** [comment] 2023-09-21 19:50
I have the same issue... try the common login URL but still the same issue

**Comment by zomchak-code** [comment] 2024-01-30 23:32
@hf 
You mentioned this issue should be reopened if `scopes: 'email'` doesn't solve the problem. 

The problem still exists, and can be reproduced. I can see a lot of people experiencing this. Let me know if you can reproduce this and if this issues should be reopened or a new created.

I'm pretty sure I've checked everything on the setup side and the access is really in granted, but this error still persists

## To reproduce

- Follow: https://supabase.com/docs/guides/auth/social-login/auth-azure
- Sign in with NON personal Microsoft account
  - During sign in url should be `https://login.microsoftonline.com`, NOT `https://login.live.com`
  - The issue is not reproduced for personal accounts, only for Directory accounts


<img width="1373" alt="Screenshot 2024-01-30 at 18 29 11" src="https://github.com/supabase/gotrue/assets/127699216/5f9d3748-4708-4f9a-9ade-fc8dbe6649ae">
<img width="1402" alt="Screenshot 2024-01-30 at 18 29 18" src="https://github.com/supabase/gotrue/assets/127699216/62e4ace4-9851-4104-baac-d40ae5052f9c">

**Comment by hmnd** [comment] 2024-02-05 10:41
@zomchak-code I'm experiencing the same. Given #292 from 2021 is still open, I'm confused what the tenant URL field in Supabase is even for..

**Comment by althaf004** [comment] 2024-02-08 03:52
I have the same issue. please reopen this ticket.

**Comment by hmnd** [comment] 2024-02-08 04:21
@althaf004 does [the comment above](https://github.com/supabase/gotrue/issues/550#issuecomment-1262058897) not fix it for you?

**Comment by abs** [comment] 2024-02-16 06:43
Without any modifications on our end, sign in with Azure is breaking with `?error=server_error&error_code=500&error_description=Error+getting+user+email+from+external+provider` - tried everyhing I could think of and all suggestions across this and similar issues, nothing is working so far.

**Comment by encima** [comment] 2024-02-16 17:47
Reopened, thanks for commenting on this. Looking into it!

**Comment by dzoba** [comment] 2024-02-22 19:53
Thanks @encima ! This kills Azure signups for us and makes us look quite bad in front of our customers who previously were able to use Azure auth to sign in but now are forced to send magic links as a fall back until this is fixed.

**Comment by hmnd** [comment] 2024-02-22 19:56
@abs / @dzoba in my case, I initially fixed this by adding the `email` scope, but then a few days later it broke again, but that time it was as a result of an expired client secret. Might be worth double checking that your secret is not expired either?

**Comment by abs** [comment] 2024-02-22 20:04
> @abs / @dzoba in my case, I initially fixed this by adding the `email` scope, but then a few days later it broke again, but that time it was as a result of an expired client secret. Might be worth double checking that your secret is not expired either?

We've been using the `email` scope from the beginning, so no changes there. Our secret was good, but I created a new one just to make sure; still broken.

**Comment by encima** [comment] 2024-02-22 20:42
As an update, the Auth team are aware and looking into the issue currently; it was not an easy one to reproduce but it is being actively worked on!

**Comment by encima** [comment] 2024-02-23 06:53
@dzoba Just to make sure this issue is only impacting the same setups, can you confirm:
1. You are not using a personal Azure account
2. You do not have a custom tenant
3. Your Entra URL is `https://login.microsoftonline.com/common`

Thanks!

**Comment by abs** [comment] 2024-02-23 06:55
> @dzoba Just to make sure this issue is only impacting the same setups, can you confirm:
> 
> 1. You are not using a personal Azure account
> 2. You do not have a custom tenant
> 3. Your Entra URL is `https://login.microsoftonline.com/common`
> 
> Thanks!

@encima the answers here are the same as in our email exchange - same product :D

**Comment by encima** [comment] 2024-02-23 10:39
Hello folks,
We have reproduced and found a reason, although it might not be fun:
1. Gotrue is right, there is no email
2. On a new tenant, new users have their UPN set but not their email. Manually editing their properties to add an email allowed a successful signin
3. Tenants can be configured to allow [email as an alternative login](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-use-email-signin) but I am unsure if that helps so much here
4. This can also be an issue for users where the email is present in their profile but the account is not verified (or the domain is not)

For those experiencing this, can you confirm this is the same behaviour you see? 
What we know so far
- Does not happen with personal accounts - expected as email is required
- Does happen with multitenant and single tenant - which means it is likely the individual users or the tenant settings not sending/setting the email

**Comment by sethtjf** [comment] 2024-02-23 13:56
I'm experiencing this issue. I was testing it with a new account that I created at Microsoft (a new tenant). I could try adjusting the settings to see if it works, but it does seem dependent on the tenant or user, which makes it too risky for me to use as a sign in method without providing an explanation to my potential users. Obviously I'd prefer to avoid this. It doesn't seem like there is a fix we could do on our ends to fix this, is that what the team thinks as well?

**Comment by encima** [comment] 2024-02-23 14:00
That is the current thinking (but it is not guaranteed).
From my AD (Entra) knowledge, I do not see a way to configure a tenant to
force/map an email. Entra also handles this with syncing methods and
Personal accounts but, when you allow multi-tenant, it is up to how they
have configured their tenants, it seems.

**Comment by sethtjf** [comment] 2024-02-23 14:28
In that case, it's entirely possible for this to be a non issue for some users wanting to sign in with their Microsoft account. The trouble is that we won't know until they try and fail. I haven't had a chance to go through the article you linked. Does that contain instructions on what a tenant would need to setup to get it working? If I could at least provide that as a reference I think I'd be comfortable enough to enable AD as a login option.

**Comment by abs** [comment] 2024-02-23 14:49
@encima do we know what caused it to suddenly stop working? It's strange, because azure multi-tenant auth with email was working after the publication of the linked article, which suggests Microsoft _did some stuff_, but may not know about it.

**Comment by encima** [comment] 2024-02-23 20:54
I have been looking at their changelogs but don't see anything apart from their mention of UPN and emails. Unless there is some new claim or similar that I am missing. 

For those with Azure support contracts, I would reach out to them please (and report back!)

**Comment by Kraktoos** [comment] 2024-02-26 16:24
Also experiencing this and can't use Entra URL `https://login.microsoftonline.com/common` because I want the application to only be accessible from a specific organization (in this case a school).

I coded this website around this time last year for a yearly event and was hoping I could re-use it. Hope this gets fixed soon!

**Comment by encima** [comment] 2024-02-27 06:28
Thinking on this some more, this is still a viable login method as the error does point to the issue, which can then be caught and the feedback for the user to set the email can be shown.

I believe some of you are reaching out to Microsoft about this, so please do update here with their response (particularly on what changed recently for this). We will keep this open while it is being tracked

**Comment by alexleetc28** [comment] 2024-03-09 18:09
It seems my Azure AD login is not working anymore after the PR "https://github.com/supabase/gotrue/pull/1269 use OIDC ID token for Azure".
My current workaround is to roll back to gotrue `2.101.2` / supabase cli `1.121.1`.

**Comment by dabbijak** [comment] 2024-03-16 11:21
I have been experiencing this issue since trying to get azure login to work for my website. Its a new project with a new Azure tenant.

I was able to get Azure to return email and Supabase to create a user by manually changing the url on the input password page. The url string "scope=openid" needs to be changed to "scope=openid,email" before submitting the password.

This behaviour seems to conform with the Azure manual that scope should by minimum include openid. Other scopes such as email and profile can be added in addition. 

https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc#openid-connect-scopes

After deleting the user in Supabase I tried to set the option in signInWithOAuth to "scopes: 'openid,email'" but it had no effect and the issue persisted as before.

Hope this helps for further troubleshooting.

**Comment by encima** [comment] 2024-03-19 04:45
HI @dabbijak 
Thanks for the steps, the `email` scope is already documented in our main docs [here](https://supabase.com/docs/guides/auth/social-login/auth-azure#add-login-code-to-your-client-app). The issue is with AD not returning the email address in the response (unless it has been manually set by the Org owner or the user themselves) as they are not mapped.

As this is an AD issue, primarily, I would opt to close this until Microsoft is able to respond with a fix. If people disagree with the decision and want to keep it open, please react with 👎 (to save commenting noise) and we can reopen!

**Closed by encima** 2024-03-19 04:45 UTC
Labels: bug, hacktoberfest, auth
