### ISSUE TITLE
Multi-factor authentication

### ISSUE THREAD

**Issue by malobre** [supabase/gotrue#14] opened 2020-08-17 16:10 UTC
**I'm submitting a ...**
- feature request

**Summary**
MFA would be a very nice addition to the `auth` module.

Here are two standards that I think should be supported:
- [ ] [HOTP](https://tools.ietf.org/html/rfc4226) and [TOTP](https://tools.ietf.org/html/rfc6238) (e.g Google Authenticator, FreeOTP)
- [ ] [FIDO U2F](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-README-v1.2-ps-20170411.txt) (e.g YubiKey, Google Titan Key)

**Comment by icecoconut** [comment] 2021-07-14 09:13
any ETA? :D

**Comment by minecraftchest1** [comment] 2021-08-20 16:58
Any plans to support WebAuthm?

**Comment by Bryanoxx** [comment] 2022-03-17 16:37
Hello ! I'm using Supabase since some months and I love it !

I'm dealing with crypto and exchanges API on my website, so naturally some of my users asked for a 2FA and by searching how to do it I found this issue, so I'm here to confirmed the need of a 2FA for supabase sign in ✅

I thought about doing my own TOTP system but it cannot be secure enough since Supabase will always give the accessToken with a proper email and a password given to it.
If there is a leak of password for one of my user, a guy can always use `supabase.signIn` directly into the console of my website and have the acessToken, so a custom TOTP asking process will always be not secure enough, it needs to be implemented by supabase directly to be 100% secure.

That's all, thank you for the great work 👋

**Comment by marcoshw** [comment] 2022-05-27 23:18
I love supabase too, the only reason i`m not using it for my current project is because the lack of MFA. Any ETA?

**Comment by J0** [comment] 2022-06-01 05:59
We're working on it! Out of curiosity, which aspect of MFA are you hoping to integrate(e.g. TOTP authenticator, SMS, email)?

Can't say much but there'll be updates on the feature before our next launch so keep your eyes peeled for then... 👀

**Comment by Deliana90** [comment] 2022-06-01 08:51
I hope for TOTP authenticator, because that more independent so that more secure and doesn't need to waiting message to be received.

**Comment by RichiCoder1** [comment] 2022-07-01 20:25
Just came here from the blog post and wanted to voice my support specifically for TOTP and especially WebAuthn.

A long term stretch of being able to fire off a push notification would be awesome too, but I don't think it's as easy or reasonable to implement.

Okta has a pretty nice breakdown of the various MFA security options available today: https://help.okta.com/en-us/Content/Topics/Security/mfa/about-mfa.htm

**Comment by J0** [comment] 2022-07-02 01:55
@RichiCoder1 We've noted your feedback -- the table  in the link you've provided gives quite a nice comparison so thanks for that!

**Comment by J0** [comment] 2022-07-04 17:32
Hey @steffenstolze  yup you are right, if you have MFA enabled on the Social Provider and you are logging in with your social provider then you will have to use MFA.

However, this wouldn't cover all cases(e.g. email/password) which may be needed for compliance purposes or  general security reasons

**Comment by steffenstolze** [comment] 2022-07-04 17:40
@J0 Absolutely! A complete solution that covers all use cases would be the best, of course 👌🏻

**Comment by edardev** [comment] 2022-07-27 19:51
Is the 2FA feature ready yet? I am building a system that needs 2FA and was wondering if the GoTrue API has this feature or should I use something else like ORY/Kratos?

**Comment by kangmingtay** [comment] 2022-09-07 13:16
Hey everyone, @J0 is working on this feature in gotrue and you guys can check out the `gotrue/mfa_v1` branch for the implementation details. We have also opened up an [early-sign up list](https://airtable.com/shrjcc9zi0RduHLIx) if you are using Supabase and looking to try out MFA in a project.

**Comment by J0** [comment] 2023-01-20 08:42
Hey team,

Going to close this issue since TOTP MFA has landed in prod. If anyone has issues please feel free to reach out. 

Thanks!

**Closed by J0** 2023-01-20 08:42 UTC
Labels: go, team

**Comment by J0** [comment] 2023-01-20 08:43
For Webauthn MFA and Passkey support please follow #92

**Comment by tomekit** [comment] 2023-05-06 20:02
Since initial feature request mentioned U2F, just a question, is it going to be implemented?

**Comment by kangmingtay** [comment] 2023-05-09 10:03
hi @tomekit, it's on the roadmap but we don't have a timeline for this yet as we are prioritising other features such as webhooks / anonymous logins over U2F right now

**Comment by J0** [comment] 2024-04-17 10:49
Hey @ProductOfAmerica, 

Thanks for the feedback - could we trouble you to head over to #92 to add feedback and/or thoughts?

**Comment by pierfreeman** [comment] 2025-05-22 16:47
Hi, and thanks for the great work on this project.
Apologies if this has already been discussed — if there's an existing issue or thread covering this topic, I'd appreciate it if you could point me in the right direction.

Are there any plans to support email-based OTP as a second factor for MFA?
While authenticator apps and phone-based methods are solid options, some of my users prefer receiving OTP codes via email. However, due to security policies, I can't rely on passwordless email login — I specifically need email OTP to be used as an MFA factor, not as a primary login method.

Thanks in advance!
