### ISSUE TITLE
User created via `supabase.auth.admin.createUser` cannot login via OAuth

### ISSUE THREAD

**Issue by timdiacon** [supabase/gotrue#937] opened 2023-01-26 14:56 UTC
# Bug report

User created via `supabase.auth.admin.createUser` cannot login via OAuth

## To Reproduce

- Create a new user within an edge function on the server using `supabase.auth.admin.createUser`
- Logout and then try and login on client using `client.auth.signInWithOAuth` with google as the provider
- The application doesn't seem to recognise a user with that email exists and attempts to create a new user which causes an error message "Database error saving new user"

## Expected behavior

- The user should be logged in

## Additional context

- The user can login as expected if you send a magic link
- Login with OAuth still doesn't work after email is verified via login with magic link
- Passing `email_confirm: true` to the original auth.admin function doesn't solve the problem

**Comment by carlosdp** [comment] 2023-02-09 05:31
I'm having this issue too.

1. Invite a user via email using "inviteUser" in supabase-js
2. They accept invite, subsequently login with Google using exact same email
3. Supabase attempts to create a new user, instead of logging in the existing one, which fails with duplicate key.

Weird part is this worked earlier today for an existing user using email provider, did something change recently?

**Comment by carlosdp** [comment] 2023-02-09 05:35
I'm unfamiliar with this codebase, so not sure, but this commit from 3 weeks ago seems like it could be the culprit https://github.com/supabase/gotrue/commit/8ddf54b21263cc88d05ad637a2d614f1389a8482

@kangmingtay any ideas here?

**Comment by mardix** [comment] 2023-02-12 01:30
Isn't that an expected behavior? 
Shouldn't the "new/invited" user connect their account separately with google so the accounts can match?

**Comment by carlosdp** [comment] 2023-02-12 12:48
> Isn't that an expected behavior? 
> 
> Shouldn't the "new/invited" user connect their account separately with google so the accounts can match? 

Right, and that'a not possible without the change that was out into master a few weeks ago (which I'm not sure has hit the Supabase hosted service yet)

**Comment by kangmingtay** [comment] 2023-02-13 01:58
@carlosdp yes, you are right. We still haven't deployed the fix to production yet but will look to do it in the upcoming week.

**Comment by carlosdp** [comment] 2023-02-22 18:02
> @carlosdp yes, you are right. We still haven't deployed the fix to production yet but will look to do it in the upcoming week.

Great! Will you close this issue when that happens, so we know it's ready?

**Comment by J0** [comment] 2023-03-01 03:37
Hey @carlosdp,

We've just rolled out a fix - could you let us know if the issue persists?

Thanks!

**Comment by d-e-h-i-o** [comment] 2023-03-05 19:58
@kangmingtay @J0 Any updates yet on this issue? Thank you for looking into it!

**Comment by J0** [comment] 2023-03-06 01:44
Hey @d-e-h-i-o ,

The fix has been rolled out partially, will update you again once it’s been fully rolled out. If you’re in a rush, feel free to email support with your project ref and we’ll let you know if your project has received the patch

**Comment by J0** [comment] 2023-03-22 14:53
Hey all,

We've rolled out a patch. Could you please try again and let us know if it works for you? Thanks

**Comment by J0** [comment] 2023-03-30 06:08
Hey team, 

Going to close for now but feel free to re-open if there are still issues

**Comment by d-e-h-i-o** [comment] 2023-04-28 15:23
@J0 I'm still experiencing the error, with a new project. Same `500: Database error saving new user` error that @muhammadzadeh described. So it looks like this issue is not solved yet.

**Comment by kangmingtay** [comment] 2023-05-02 10:53
@d-e-h-i-o can you please reach out to us at https://app.supabase.com/support/new so we can investigate the issue with your project?

**Comment by kangmingtay** [comment] 2023-05-16 09:13
hi @d-e-h-i-o, seems like this issue has been resolved already through our support channel - please feel free to reopen it and write back to us if you're still experiencing this issue.

**Closed by kangmingtay** 2023-05-16 09:13 UTC
Labels: bug, auth
