### ISSUE TITLE
Cannot integrate Postmark API with Supabase

### ISSUE THREAD

**Issue by shivam-51** [supabase/gotrue#304] opened 2021-12-19 04:55 UTC
# Improve documentation
I want to integrate [Postmark](https://postmarkapp.com/)(an email service) api with that of Supabase such that any email action from Supabase should trigger the PostMark endpoint and that should finally send the mail to the respective email ids.

I see some discussion has been done on that regard(#109 and #133)  but the whole discussion is very vague and I cannot find anything in the docs referencing this. What is the way to add that endpoint in Supabase dashboard? any link to documentation is also greatly appreciated.

**Comment by kangmingtay** [comment] 2021-12-20 15:31
hi @shivam-51, you can use the `/generate_link` endpoint in gotrue or the method [generateLink](https://supabase.com/docs/reference/javascript/auth-api-generatelink) in supabase-js to generate a confirmation, invite, recovery, magic link and send it your users using the postmark api.

**Comment by kangmingtay** [comment] 2022-01-05 09:35
hi @shivam-51, let me know if this worked for you, else imma close the issue for now

**Comment by chipilov** [comment] 2022-01-13 16:32
@kangmingtay Unless I am missing something, I think this issue should be re-opened because it does NOT address the scenario of the initial sign-up confirmation.

The problem is that, currently, if we want e-mail confirmations BEFORE the user can sign-in, Supabase will always send a confirmation e-mail using the template from the Dashboard and NOT a template defined in the custom SMPT service (many such services provide their own templates with rich editors).

I think there should be a way to enable e-mail confirmations WITHOUT having Supabase send an actual email (this can be done in a trigger). That way, we can still take advantage of GoTrue's logic for generating confirmation tokens and disallowing sign-ins before confirmation, but we can leverage custom templates.

**Comment by chipilov** [comment] 2022-01-26 09:40
@kangmingtay ping - can we re-open this issue or do you think I need to open a new one?

**Comment by J0** [comment] 2022-01-26 10:12
Hi @chipilov,

I just joined the team and will be working on GoTrue with @kangmingtay 

It's a nit but I think it would be better if you opened a fresh issue. Though the scenarios seems similar, the original request seems to be centered around the documentation while the issue above described seems to be a feature request. 

Happy to re-open if you feel strongly for it though. Lmk!
Joel

**Comment by kangmingtay** [comment] 2022-01-26 10:31
Hey @chipilov, just to clarify - what is your use case here? It would be great if you could clarify on what you mean by the following statements:

> ..does NOT address the scenario of the initial sign-up confirmation.

what do you mean by the initial sign-up confirmation? 

> ..enable e-mail confirmations WITHOUT having Supabase send an actual email 

Personally, I feel that this isn't great from the DX perspective because it seems to account for a very specific edge case and would cause more confusion. 

> That way, we can still take advantage of GoTrue's logic for generating confirmation tokens and disallowing sign-ins before confirmation

I'm probably missing something here but doesn't the `/generate_link` template handle this for you? It generates a confirmation token, doesn't send an actual email and it disallows sign-ins before confirmation. You can still use your custom template and include the link generated inside the template.

Would be great to hear back from you!

**Comment by chipilov** [comment] 2022-01-26 11:35
Hey @kangmingtay, I think there are 2 specific use cases that I am trying to address:

1. Re-sending sign-up e-mail confirmation

For whatever reason, e-mail delivery is not the most reliable process, so most apps show a button like "Resend e-mail confirmation" to allow the user to trigger another e-mail if they never received the first e-mail in a reasonable time (e.g. a couple of minutes).

The problem with this scenario is that while Supabase automatically sends the first e-mail when the user signs-up, any subsequent confirmation e-mails MUST be sent by custom server-side code (via the usage of generate_link). Aside for the fact that the same action (sending e-mail confirmation) is basically handled in 2 different ways, there is also the issue of how to ensure that the e-mail sent by Supabase looks exactly the same as the e-mail sent by the custom server-side code. Unless I am missing something, your best bet is to basically copy-paste the template you have in Supabase to whatever templating engine you use by the custom e-mail provider (or vice-versa).

This problem would be solved or at least alleviated by any of these:
  (a) Supabase allows calling parameterized HTTP hooks on signup/password reset/etc instead of forcing you to use templates from the dashboard. That way, one can simply provide the HTTP hooks from their e-mail provider and use a single set of templates defined in the provider (you'd still need custom server-side code for re-sending of the e-mails, but at least you would NOT need to handle 2  sets of templates for the same thing);

  (b) Supabase introduces a dedicated API for actually sending emails, NOT just generating links - this would improve this particular scenario since you would just use the templates in the Supabase dashboard. However, this would NOT solve the second scenario described below and it would also prevent you from using the templating engine from your custom e-mail provider (which, with all due respect, usually has better authoring experience than the Supabase dashboard);

  (c) Supabase introduces the option to enforce e-mail confirmations but does NOT send e-mails automatically and instead leaves all that to the developer. I agree with you that this is NOT very good DX, especially given that you run into transactional problems where the trigger and the generate_link code see different data (because the trigger sees data from within the current transaction while the generate_link code does NOT see the data from the transaction);

2. Maintaining a single set of templates for all of the app's needs

Currently, Supabase allows you define e-mail templates ONLY for auth use cases (e.g. sign-up, invite, etc). However, many apps (especially online marketplaces) need other kinds of templates, e.g. payment reminders, order confirmations, etc. With the current Supabase flow, this means that a developer needs to maintain 2 sets of templates (with 2 different authoring experiences) - the Supabase auth templates in the Supabase dashboard and all other templates.

This problem would be solved or at least alleviated either by solution (a) above (not sure if there is another approach).

IMHO, the first scenario is relatively common for any app while the second scenario is dependent on the type of app, but still pretty common for marketplace-type apps.

I hope this makes things clearer:
  - if so, I would be happy to open a separate ticket (or two) for these scenarios;
  - If not, I would be happy to clarify even further (maybe it would be better to hash it out over Discord, but I don't mind continuing here)

**Comment by kangmingtay** [comment] 2022-01-26 17:53
Hey @chipilov, thanks for taking the time to explain the cases in detail, i really appreciate it! Yeah, I get what you mean, for (1), i like the option (a) you suggested which is to use webhooks to to send the emails from their email provider. 

As for (2), i agree that our email templating flow is quite restrictive currently. If we were to go with the webhook approach for (1), we can change the email templating page to allow users to dynamically create their custom email template for specific cases and attach it to a webhook endpoint. When the webhook is triggered on an auth event, the respective template will be sent out depending on which email action is triggered. 

Let's keep this thread open - this is really good feedback for improving the auth email templating experience.

**Comment by yowzadave** [comment] 2022-03-05 03:13
I agree with the points @chipilov raises above! Also, if there are cases where the built-in templates are unsuitable (no support for i18n, no way to extend with additional dynamic variables, etc.) there appears to be no straightforward way to replace them with a more robust custom solution.

**Comment by chipilov** [comment] 2022-07-15 13:40
> Hey @chipilov, just to clarify - what is your use case here? It would be great if you could clarify on what you mean by the following statements:
> 
> > ..does NOT address the scenario of the initial sign-up confirmation.
> 
> what do you mean by the initial sign-up confirmation?
> 
> > ..enable e-mail confirmations WITHOUT having Supabase send an actual email
> 
> Personally, I feel that this isn't great from the DX perspective because it seems to account for a very specific edge case and would cause more confusion.
> 
> > That way, we can still take advantage of GoTrue's logic for generating confirmation tokens and disallowing sign-ins before confirmation
> 
> I'm probably missing something here but doesn't the `/generate_link` template handle this for you? It generates a confirmation token, doesn't send an actual email and it disallows sign-ins before confirmation. You can still use your custom template and include the link generated inside the template.
> 
> The only scenario I can think of is if the user wants to leverage the email sending functionality of gotrue but at the same time, they want to use their custom smtp provider and make use of rich templates. Using the `/generate_link` wouldn't work for them since they prefer not to handle the email sending logic themselves.
> 
> Would be great to hear back from you!

@kangmingtay I misunderstood you about the usage of the ```/generate_link``` API, but now I understand that you can actually sign-up users (i.e. add them to the ```auth.users```) table with this API and NOT just generate links for existing users. Indeed, this will help my scenarios because Supabase will NOT automatically send sign-up e-mails in this case and I will have complete control over sending of the emails.

For anyone interested in using this approach, there are a few important things to keep in mind:
  - unlike the ```signup()``` JS API, the ```/generate_link``` API ONLY works with the ```service_role```, so one would need to create a custom signup API in the app backend and call the API from there;
  - unlike the ```signup()``` JS API, the ```/generate_link``` API returns a 422 HTTP error when trying to signup a user which already exists (the JS API returns fake data);
  - unlike the ```signup()``` JS API, it seems like there is no rate limiting for the ```/generate_link``` API (@kangmingtay please, correct me if I am wrong about this one);

**Comment by vincentjflorio** [comment] 2023-01-07 18:27
@chipilov Thanks for mentioning the service role bit. It's documented that way for admin functions but I completely forgot and was wondering why all my returns were coming back null :)

**Comment by J0** [comment] 2023-03-20 08:58
Hey all,

Re-read the thread and it seems like the issue has been resolved (CMIIAW). As for next steps, we will be looking into parameterized HTTP hooks so feel free to follow along on our changelog/newsletter.

Thanks!

**Closed by J0** 2023-03-20 08:58 UTC
Labels: documentation
