### ISSUE TITLE
sign in via apple using authorization code / email (rest api) not web flow

### ISSUE THREAD

**Issue by johndpope** [supabase/gotrue#807] opened 2022-11-14 10:02 UTC
# Feature request
currently the sign in via apple is only on browser - we need a native solution.
I've crafted a sample in javascript / nodejs 
https://github.com/johndpope/Sign-in-with-Apple-for-supabase/

we want to send the authorization_code + email to backend - and return the existing user - or sign up new one.

## Is your feature request related to a problem? Please describe.
https://github.com/supabase-community/gotrue-swift/issues/4

A clear and concise description of what you want and what your use case is.

## Describe the solution you'd like

sign in via rest api - as documented here 
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api

## Describe alternatives you've considered

the web based browser session is not sufficient.

## Additional context

see readme

**Comment by hf** [comment] 2023-01-25 15:23
This is a duplicate of #434.

**Closed by hf** 2023-01-25 15:23 UTC
Labels: enhancement

**Comment by johndpope** [comment] 2023-02-03 00:13
so - there's seems to be a misunderstanding. 
I want to sign into ios apple login in swift with uikit - and get the authorization code NATIVELY. 

the swift repo here is based off sign with apple from apple.
https://github.com/johndpope/Sign-in-with-Apple-for-supabase/

When you successfully sign in - you get an authorization code from Apple.
 THIS IS APPLE SWIFT CODE - THIS IS THE METHOD FOR RECEIVING THE AUTHORIZATION FROM APPLE LOGIN.
![image](https://user-images.githubusercontent.com/289994/216479440-c2c47771-6752-46f9-b460-d80df9afc10e.png)


the PR you mention in 434 seems to be for javascript.
is there backend work that's related? 
I just want to hit the gotrue api - and send this authorziation code.

I dont need/want any captcha.
  gotrue_meta_security: { captcha_token: options?.captchaToken },

@kangmingtay - this doesn't seem to help native login.
I'm not interested in sign in via a browser / webflow.
