### ISSUE TITLE
[Feature request] auth.resendConfirmationEmail

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/gotrue#312] opened 2021-07-03 18:53 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Occasionally, users don't receive email confirmation emails, or the emails go to spam. Or they may have created an account a week ago and are just now signing in. Or potentially, your site originally did not require email confirmations and now you wish to enforce it.

In short, there are many reasons why you may wish to resend the email confirmation email. Currently, there's not an API to do this.

## Describe the solution you'd like

```js
supabase.auth.resendEmailConfirmation("email@example.com")
```

## Describe alternatives you've considered

Currently, there are only two ways to achieve this functionality (neither of which are ideal).

1. **Send a password reset link**. Of course, many users don't want to immediately reset their password.
2. **Send a magic link**. This will work, though you'll be using a different email template. Instead of sending a confirmation email, you'll be sending a log-in email. Functionally this is the same, but users could be confused because the email's contents are not exactly what they were looking for. You could copy the password confirmation email into the magic link template, but then you can't use the magic link.

## Additional context

This is a low-priority issue, though I have a feeling this will be decently easy to implement.

**Comment by travisanderson** [comment] 2022-03-26 22:29
still needs to happen.

**Comment by travisanderson** [comment] 2022-03-26 22:29
still needed.

**Comment by bicijay** [comment] 2022-06-21 17:22
It doesnt make sense that a feature so important like that one was not implemented in the email auth. Are there any workarounds for this issue? Talking about a scenario where i use auth.update({email}) but the email does not arrive so i have to send it again.

**Comment by cliveportman** [comment] 2022-08-31 09:08
Is this still not implemented? It seems a glaring omission to me, especially as the confirmation link max expiry is 24 hours!

**Comment by madeleineostoja** [comment] 2022-09-08 03:58
Just went to setup email verification on my beta app and I am dumbfounded such a basic feature is missing. Emails hitting a spam filter or just not getting done within 24hrs by the user is extremely common, not being able to resend it is bonkers

**Comment by burggraf** [comment] 2022-09-08 12:08
I believe if you just send another magic link, that will verify the email.  So if you can't log in because you haven't verified, you can just log in with a magic link.

**Comment by cliveportman** [comment] 2022-09-08 13:38
> Just went to setup email verification on my beta app and I am dumbfounded such a basic feature is missing. Emails hitting a spam filter or just not getting done within 24hrs by the user is extremely common, not being able to resend it is bonkers

Exactly my issue. But as @burggraf said, you can resend by creating the user again, which is what I do. If they're already created, it just re-sends the invite email. I'm going to add a trigger to them accepting the invite, to update a column on their profile so I know whether they're confirmed or not. I'll use that to check whether the 'resend invite' button needs to be shown for each user.

**Comment by madeleineostoja** [comment] 2022-09-08 23:00
Ah okay that's good to know re: recreating the user. I think that's a cleaner approach than a magic link, which has a different goal/messaging to the user than confirming an email.

**Comment by 413n** [comment] 2022-09-08 23:24
You need to call again `supabase.auth.signUp` with also the credentials including the password?
In my use case I "redirect" the user to another page, so I cannot resend the credentials the user originally inserted.
A function to resend the email (maybe also with a configurable time-to-wait before a new email can be sent) would be really needed.

**Comment by mathiasayivor** [comment] 2022-09-23 01:31
How can this simple but essential feature be missing for such a platform? I mean supabase is supposed to be a platform that you can write a full application on.

**Comment by hf** [comment] 2022-09-29 13:20
Hey everyone, we feel your pain and we're doing the best we can. I've added this to our backlog and we'll try to pick it up soon.

**Comment by nathaneidelson** [comment] 2022-11-02 00:45
@hf reiterating here how badly we need this feature. It's a pretty big dealbreaker to ask the user to re-enter in their password just so that I can call .signUp() just so that I can send them another confirmation code ... this is **ESPECIALLY** important since you force a max 24hr link time. At least let me change it to 14 days or something as a short-term hack.

**Comment by cliveportman** [comment] 2022-11-02 07:47
I recommend switching to the v2 version of the API and using the 6-digit OTP. It has solved all of these problems for me, in the absence of an official solution.

**Comment by madebyfabian** [comment] 2022-12-11 14:35
+1, would really like to see this. In the meantime:

https://github.com/supabase/supabase/discussions/3526#discussioncomment-4371715

**Comment by florianwalther-private** [comment] 2022-12-23 19:47
> I recommend switching to the v2 version of the API and using the 6-digit OTP. It has solved all of these problems for me, in the absence of an official solution.

But it won't work with password signup, right? Because `verifyOtp` doesn't send another token if the account already exists.

**Comment by ZhenFTW** [comment] 2023-01-03 06:26
I think to do it, we need additional type in GoTrue generate_link api named 'resend' with email and password as parameter. The only type that can generate new link when user is already signup in generate link api is type 'recovery' but it is not the way to do it since it's for changing the user password.

**Comment by alphakex2** [comment] 2023-01-09 06:42
I just tried the 6 code otp via email here is the code  const { error, data } = await supabase.auth.verifyOtp({
      email: email,
      type: "signup",
      token,
    }) but I get the token expired message I don't know what I'm doing wrong since the code entered and the code sent to the email address on signup match. Why such a crucial feature as resending new confirmation assuming the token expiry is true is a  deal breaker

**Comment by florianwalther-private** [comment] 2023-01-09 22:05
> I just tried the 6 code otp via email here is the code const { error, data } = await supabase.auth.verifyOtp({ email: email, type: "signup", token, }) but I get the token expired message I don't know what I'm doing wrong since the code entered and the code sent to the email address on signup match. Why such a crucial feature as resending new confirmation assuming the token expiry is true is a deal breaker

Maybe your problem is related to this: https://github.com/supabase/gotrue/issues/876#issuecomment-1368064459

**Comment by kangmingtay** [comment] 2023-01-24 05:44
Hey everyone, apologies for the delay, I've been working on getting this in the upcoming weeks so stay tuned! It seems like there are 2 problems here which I'll attempt to resolve:

1. Calling the `signInWithOtp` method for a new user sends a confirmation email initially. But if the user isn't confirmed yet, calling `signInWithOtp` subsequently as an attempt to "resend the confirmation email" will send the "Reset Password" email template instead. This is definitely not ideal since the "Reset Password" template could be different from the "Confirmation signup" email template. This has been fixed in #889 and should land in all Supabase projects in the upcoming weeks.
2. The ability to resend email confirmations (which is also the main topic on this thread). I've started a PR (#912) to address this and the DX should look like this in the gotrue-js client library:

```js
await resendConfirmationEmail({ email })
```

```bash
curl -X POST "http://localhost:9999/resend_confirmation" -H "Content-Type: application/json" -d '{"email": "foo@example.com"}'
```

The endpoint will return an empty object regardless of whether the user exists / is confirmed (similar to requesting for a password recovery email). 

Thanks everyone again for your patience and for taking the time to comment on this thread and bring this to our attention.

**Closed** 2023-02-13 16:06 UTC
Labels: enhancement, hacktoberfest

**Comment by kangmingtay** [comment] 2023-02-13 16:07
Just merged the PR in, will be looking to add the client library bindings to the supabase-js library soon! We'll need some time to deploy this to all hosted projects on Supabase but I'll update the thread once that's done.

**Comment by dmudro** [comment] 2023-03-21 17:23
hi @kangmingtay thanks for the update in Feb. I appreciate this issue is now closed but I wonder if the new API `auth.resendConfirmationEmail` can be used on the JS client or server or at all?

we have a little UI link after the user registers with email, e. g. "didn't receive the confirmation email? resend now.". I am looking into ways how to implement this resend flow as we are migrating from Firebase. thanks!

**Comment by kangmingtay** [comment] 2023-03-22 00:27
hey @dmudro, we're in the process of adding it to the JS client lib so stay tuned!

**Comment by tcxcx** [comment] 2023-04-10 21:06
Hi @kangmingtay I am at the exact same point state as @dmudro is here. I wanted to know soon this feature will be added to the js library to check whether to leave this feature out of our auth process or keep in the roadmap for our coming sprint. Thank you!

**Comment by cwierzbicki00** [comment] 2023-05-04 20:42
@kangmingtay I do not see this in the JS client lib yet. Any updates here? The OTP work around is sad for us :(

**Comment by andrhubb** [comment] 2023-07-14 22:38
https://pub.dev/documentation/gotrue/latest/gotrue/GoTrueClient/resend.html

What about reutilising this?
