### ISSUE TITLE
Add a redirectTo parameter when updating an user email

### ISSUE THREAD

**Issue by JonathanPicques** [supabase/gotrue#604] opened 2022-08-12 10:32 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

As of now, updating the authenticated user's email sends a mail with a redirection to the Site URL you define in the supabase project settings

![image](https://user-images.githubusercontent.com/1839757/184336810-f67b493c-f6c8-404d-b5ea-56ec6d7c14ee.png)

It would be nice to have a `redirectTo` in the update method of the GoTrue client (like with `resetPasswordForEmail`)

## Describe the solution you'd like

Add a second parameter to update to allow passing `redirectTo`

**Comment by atzmanuel** [comment] 2022-08-23 14:58
I've opened an issue about this yesterday on [supabase repo](https://github.com/supabase/supabase/issues/8584) and the issue is not inside gotrue which accepts different `redirectTo`. The issue is inside gotrue-js which doesn't let you pass any `redirectTo` option. I've opened a pull request on gotrue-js [here](https://github.com/supabase/gotrue-js/pull/410)

**Comment by J0** [comment] 2022-09-14 13:47
Hey all, let's continue the discussion on the linked GoTrue-js issue. Closing for now but feel free to re-open if there are further queries.

**Closed by J0** 2022-09-14 13:47 UTC
Labels: enhancement, auth
