### ISSUE TITLE
Logout on one device prevents all other devices from getting new jwt

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#248] opened 2021-10-26 09:12 UTC
### Discussed in https://github.com/supabase/supabase/discussions/3637

<div type='discussions-op-text'>

<sup>Originally posted by **Vinzent03** October 24, 2021</sup>
I am using the dart SDK, but I think that doesn't matter.

Let's say I'm signed in on device A and B. Now I log out on Device A. This [revokes](https://github.com/supabase/gotrue#post-logout) all refresh tokens in `auth.refresh_tokens`. Now my jwt expires on device B and I want to get a new jwt by calling the [token](https://github.com/supabase/gotrue#post-token) endpoint. This requires a refresh token, this is saves on the client, but because of the log out on device A, it's revoked and doesn't work. Which causes device B to be logged out too.

So my question is, is this intended or is my workflow wrong?</div>

**Comment by wizzymotion** [comment] 2022-01-03 21:48
Any news???

**Comment by J0** [comment] 2022-01-25 07:06
Hey @wizzymotion,

Thanks for your patience so far! We've added this into our task board and we are hoping to address this within the month. Let me know if you have any further questions/concerns.

Thanks!

**Comment by msdrigg** [comment] 2022-03-29 14:18
I know this is intended behavior for GoTrue. I know supabase does their own thing with GoTrue, but on the netlify/gotrue repository readme ([here](https://github.com/netlify/gotrue#endpoints)), it clearly says

---
* **POST /logout**

  Logout a user (Requires authentication).

  This will revoke all refresh tokens for the user. Remember that the JWT tokens
  will still be valid for stateless auth until they expire.
---

I think we should consider the security implications of changing this behavior before we go forward with changing it. 

Currently, if a refresh token gets stolen from the user, users can logout and ensure that any stolen tokens are revoked. If this behavior is changed, there needs to be a way to ensure that all refresh tokens are revoked (I am ok if it is different from the current behavior, we just need to ensure that we still provide this functionality).

Additionally, logging out a user currently does not revoke the access token associated with that user (I believe from my reading of the source). This behavior needs to be clarified in the documentation or changed to meet expectations.

I think to meet all needs, it would be appropriate for `/logout` to revoke the access token used to authorize the logout, but we need seperate endpoints for `/revokeRefreshToken` and `/revokeAllRefreshTokens` to be able to ensure users can secure their api's properly.

**Comment by msdrigg** [comment] 2022-03-29 14:31
I edited my comment above for clarity, sorry to confuse the person who already read and thumbs-upped it.

**Comment by J0** [comment] 2022-09-20 05:53
Hey all,

The behaviour described is indeed intended -- logout should revoke all refresh tokens and log out all devices. It seems like the docs have been updated to reflect this as well. We will transitioning moving to use database sessions which might make it easier to allow for management of different sessions on different devices.

Going to close the issue for now but feel free to comment or request to re-open if there are still further issues.

**Closed by J0** 2022-09-20 05:53 UTC
