### ISSUE TITLE
Auth password allowed characters

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#354] opened 2022-01-21 17:03 UTC
### Discussed in https://github.com/supabase/supabase/discussions/5065

<div type='discussions-op-text'>

<sup>Originally posted by **b14ckkn19ht** January 19, 2022</sup>
Hello,

I've made the observation that e.g. registering with a "+" in the password will lead to an successfull signup, but later the user can not sign in with his password.
I've tried to look for a list of characters in the documentation, however I only found such a list for the postgres password.

Which characters are allowed in a user password?
Where is this information documented?
Or do I have a problem with the usage of the supabase-js client?

Best regards </div>

**Comment by mustafaTokmak** [comment] 2022-01-31 21:03
I couldn't reproduce this issue at my local

**Comment by J0** [comment] 2022-04-19 06:58
I couldn't quite reproduce this issue when testing on a Supabase instance with the password: `example+password` the audit log and the browser both seem to indicate that the sign up went through. It's possible that the user is using a keyboard with a different character set where '+' is slightly different(much like how " is different on english and chinese keyboards)

Need more information though. Going to close this for now -- feel free to re-open if there are further issues.

Thanks!

**Closed by J0** 2022-04-19 06:58 UTC
Labels: bug, For discussion
