### ISSUE TITLE
Disabling phone confirmation doesn't work

### ISSUE THREAD

**Issue by loama** [supabase/gotrue#320] opened 2021-09-02 20:06 UTC
# Bug report

## Describe the bug

In the console I already disabled phone confirmations but it is still trying to send them.

## Expected behavior

Should just register the users with phone and password without requiring a verification

## Additional details:
it returns `
  message: 'Error sending confirmation sms: json: cannot unmarshal number into Go struct field SmsStatus.status of type string',
  status: 400
}`

**Comment by J0** [comment] 2022-04-25 07:25
Hey! 

Thank you for taking the time to post this issue. I'm currently looking into the issue and have made attempts to replicate with the end goal of creating a patch. Could I trouble you for more information about replicating the issue? 

Here's what I've tried so far:

**Case One: With just phone number**
1. `signIn({phone_number: '12345678'})`
2. disable
3. `signIn({phone_number:'12345678'})`

Verification SMS is sent to confirm phone number

**Case Two: With phone number and password**
1. `signUp({phone_number:'12345678', password:'some-password'})`
2. disable confirmation
3. `signIn({phone_number:'123456', password:'some-password'})`

Confirmation is not sent as expected

Can I trouble you to verify if the issue reported above is the same as that observed in case 1? We'd love to know if there's another bug/case that we're missing.

Thanks so much!
Joel

**Comment by J0** [comment] 2022-05-06 06:29
Duplicate of #469 , continuing the discussion there

**Closed by J0** 2022-05-06 06:29 UTC
Labels: bug
