### ISSUE TITLE
Custom SMS Provider

### ISSUE THREAD

**Issue by ardyfeb** [supabase/gotrue#456] opened 2022-04-20 16:28 UTC
# Feature request

## Is your feature request related to a problem?

Yes. i current building app that require SMS OTP authentication. 

Due my SMS API provider not available in current Supabase supported SMS provider so i can't provide SMS OTP in my app.

## Describe the solution you'd like

Give option to use external SMS provider through webhook. 

So **when SMS OTP requested through Supabase API, then Supabase will send request to configured URL and check the condition (that will configured on dashboard)**

## Describe alternatives you've considered

Currently i not provide SMS OTP on my app, but the plan is self-hosting and add my SMS provider logic

## Additional context

None.

**Comment by kangmingtay** [comment] 2022-04-29 23:35
hi, just wondering, which sms provider are you using currently?

**Comment by ardyfeb** [comment] 2022-04-30 07:50
@kangmingtay currently using local sms provider https://nusasms.com/

**Comment by w0wka91** [comment] 2022-05-14 15:10
I guess this is an duplicate of https://github.com/supabase/gotrue/issues/385

**Comment by ardyfeb** [comment] 2022-05-14 17:29
okay, closing this

**Closed** 2022-05-14 17:29 UTC
Labels: enhancement
