### ISSUE TITLE
GitHub OAuth Sign In not working

### ISSUE THREAD

**Issue by deve-sh** [supabase/gotrue#868] opened 2022-11-26 10:22 UTC
# Bug report

## Describe the bug

When trying to login with GitHub, post-authorization by GitHub, I'm being redirected to my web app with the query params: `error=server_error&error_description=url+argument+is+missing`

My GitHub Sign In code:

```javascript
const signInWithGitHub = () =>
    supabase.auth.signInWithOAuth({
        provider: 'github',
        options: { redirectTo: window.location.origin }
    });
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable GitHub Login for your application via the steps mentioned by the official Supabase guide here: https://supabase.com/docs/guides/auth/auth-github
2. Try logging in with GitHub in your application

A link where this error can be seen: https://spot-monitoring.vercel.app/

## Expected behavior

The GitHub Sign In was working a while back, but without any changes, it stopped working all of a sudden.

## System information

- OS: [e.g. macOS, Windows] Windows
- Browser (if applies) [e.g. chrome, safari] Chrome
- Version of supabase-js: [e.g. 6.0.2] 2.0.5 and 2.1.1 (Also tried latest)
- Version of Node.js: [e.g. 10.10.0] 14.17.0

**Comment by hf** [comment] 2022-12-20 13:49
@deve-sh [Please open a support ticket](https://app.supabase.com/support/new) if you are facing an issue on a live application and you're not able to figure out the cause of the issue.

Regarding this specific issue, it may be worth checking your project's [Authentication URL Configuration](https://app.supabase.com/project/_/auth/url-configuration) for any errors.

I'll close this issue but feel free to comment further.

**Closed by hf** 2022-12-20 13:49 UTC
Labels: bug
