### ISSUE TITLE
Facebook OAuth not working

### ISSUE THREAD

**Issue by adrianhorning08** [supabase/gotrue#374] opened 2022-02-04 21:47 UTC
# Bug report

## Describe the bug

When using Facebook OAuth to login with a test user (someone other than the admin who created the Facebook App), I am getting an error and unable to login. 

Either I receive:
`
{
  "message":"An invalid response was received from the upstream server"
}`

Or: "error=server_error&error_description=Error+getting+user+email+from+external+provider"

I know that the the issue with the latter error is a user not having an email address (#214 ), but if you create a test user in Facebook, they do have email addresses.

I have tested this with another Facebook account I have created that wasn't a "test user" per se, and same thing happened. 

## To Reproduce

You will have to create your own Facebook App. *You can see the error locally, so no need to deploy it yourself.

I just followed these guides to create a quick app and Facebook Login:
[Next.js App](https://supabase.com/docs/guides/with-nextjs)
[Facebook Login](https://supabase.com/docs/guides/auth/auth-facebook)

So the steps would be...
1. Create an app (I created a Next js one)
2. Implement Facebook Login
3. Login with your admin user. Everything should be fine.
4. Try logging in with a test user by going to Roles > Test users > Create Test Users. Then try logging into your app with that test user. 
5. Should see an error. 

Heres a loom [video](https://www.loom.com/share/ec7e3632c42e40c59b1c3229b72720bd)

## Expected behavior
Should not see error and should redirect you to /accounts page. And when you revisit the home page, it should remember your session and not prompt you to login.

## System information

- OS:  macOS
- Browser: chrome
- Version of supabase-js: `@supabase/supabase-js": "^1.30.0`
- Version of Node.js: v16.13.0

**Comment by matepapp** [comment] 2022-02-06 17:06
hey! same happens with Google provider in my case.

**Comment by awalias** [comment] 2022-02-07 04:14
taking a look, thanks for the great repro steps and vid @adrianhorning08

**Comment by kangmingtay** [comment] 2022-02-09 11:35
hey @matepapp and @adrianhorning08, we have investigated the issue with this error `{ "message":"An invalid response was received from the upstream server" }` and I am able to reproduce this error with Facebook logins using a test user, but it seems to work fine with the admin user as you suggested.

The reason this happens is because we started setting the tokens in the cookies as of [this PR](https://github.com/supabase/gotrue/pull/351) which resulted in the header size exceeding the limits enforced by the API gateway. We're working on a fix for this and will notify you guys once it's out!

**Comment by matepapp** [comment] 2022-02-09 17:45
hey @kangmingtay, 

thanks for the quick and detailed response and also for the investigation. take your time and let us know how it goes 💪

**Comment by kangmingtay** [comment] 2022-02-11 06:33
hey @matepapp and @adrianhorning08, could you please email `support@supabase.com` with your project reference and I'll fix the issue for your projects, thanks!

**Comment by adrianhorning08** [comment] 2022-02-11 17:50
@kangmingtay I actually switched to firebase for the auth 😅  Project was time sensitive. Thanks so much for investigating this.

**Comment by matepapp** [comment] 2022-02-19 16:34
hey @kangmingtay, I didn't have a lot of time since my latest comment but I just checked in my side project, and seems like the issue got resolved 👍 I could log in & log out with Google without any issue. thanks for the help! I'll make sure to send an email in case it happens again.

**Comment by J0** [comment] 2022-05-06 07:36
Hey all,

It seems like this issue has been resolved for now so we're going to close this issue. Feel free to let us know if you have any concerns or if you run into this issue again.

Thanks!

**Closed by J0** 2022-05-06 07:36 UTC
Labels: bug, For discussion, provider-related-bug
