### ISSUE TITLE
Revoking a refresh token does NOT update the updated_at field in the auth.refresh_tokens table

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue#400] opened 2022-02-25 15:48 UTC
# Bug report

## Describe the bug

The ```auth.refresh_tokens``` table contains an ```updated_at``` field. It seems that this field is initialized when a new refresh token is created and is NOT updated when the token is revoked.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Using Supabase e-mail auth, log-in with a user - notice that a new refresh token is created whose ```created_at``` and ```updated_at``` fields have the same value
2. Wait for the user's JWT to be refreshed

## Expected behavior
The original refresh token is marked as revoked and its ```updated_at``` field is updated

## Actual behavior
The original refresh token is marked as revoked but the ```updated_at``` field is NOT updated.

**Comment by J0** [comment] 2023-05-22 08:36
Hey @chipilov,

Thanks for patiently waiting. This took a while to get back to. I've just done a quick test and it looks like the `updated_at` field is updated now. Here are the steps I took to reproduce:

1. Shorten JWT duration to 120 seconds
2. sign up with <myemail>@supabase.io
3. Confirm email
4. Wait for refresh token to update
5. Repeat with sign in

![CleanShot 2023-05-22 at 16 30 59@2x](https://github.com/supabase/gotrue/assets/8011761/26e9a199-eecd-47c3-8d0a-a0fb26557be8)

Perhaps it could have been a bug which has been fixed between the reporting date and now. Am going to close this issue for now but feel free to re-open the issue if you see this again.

Once again, thanks for taking the time to report an issue!

**Closed by J0** 2023-05-22 08:36 UTC
Labels: bug
