### ISSUE TITLE
Snapchat external provider login

### ISSUE THREAD

**Issue by wweevv-johndpope** [supabase/gotrue#611] opened 2022-08-19 02:45 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
signup for client / secret keys here
https://docs.snap.com/snap-kit/developer-portal/developing-your-app

I want to enable like this
```

      GOTRUE_EXTERNAL_SNAPCHAT_ENABLED: "true"
      GOTRUE_EXTERNAL_SNAPCHAT_CLIENT_ID: "111"
      GOTRUE_EXTERNAL_SNAPCHAT_SECRET: "asdf"
      GOTRUE_EXTERNAL_SNAPCHAT_REDIRECT_URI: "https://localhost:9999/callback"


```

**Comment by J0** [comment] 2022-08-22 11:06
Closing as it is a duplicate of #451

**Closed by J0** 2022-08-22 11:06 UTC
Labels: enhancement

**Comment by johndpope** [comment] 2022-09-11 04:22
drafted here https://github.com/supabase/gotrue/pull/449/files
