### ISSUE TITLE
How to confim a new email address ? 

### ISSUE THREAD

**Issue by ElouanL** [supabase/gotrue#53] opened 2020-12-28 17:03 UTC
# Improve documentation

## Describe the problem

When I update the email of a user account, I receive a "Confirm email address change" with a email_change_token.
What should I do with it? Which end point should use to validate the new e-mail?

Thank you

**Comment by awalias** [comment] 2021-01-23 09:42
duplicate of https://github.com/supabase/gotrue/issues/60 thanks for requesting @ElouanL it needs some work

**Closed by awalias** 2021-01-23 09:42 UTC
Labels: documentation
