### ISSUE TITLE
Additional redirect URLs not working reliably

### ISSUE THREAD

**Issue by heauton** [supabase/gotrue#123] opened 2021-06-24 09:37 UTC
# Bug report

## Describe the bug

URLs added in "Additional Redirect URLs" used to work but now only the URL in "Site URL" does. Also, added URLs don't seem to work right away?

## To Reproduce

A little bit hard to reproduce, but here's what I did:

1. Added http://localhost:3000 in "Additional Redirect URLs" and https://some-site.com in "Site URL"
2. Did not work for the first couple of hours, and all of sudden it worked
3. Did not touch any auth settings and...
4. After some time, tried to set http://localhost:3000 in `redirectTo` but I got https://some-site.com as `redirect_url` parameter

I tried to refresh auth settings page a couple of times to check if URLs are saved.

## Expected behavior

When I update URLs in auth settings, I should be able to use those URLs in `redirectTo` option and get that URL as `redirect_url` parameter.

## System information

- Version of supabase-js: 1.15.0

## Additional context

Possibly related to https://github.com/supabase/supabase/issues/1895

**Comment by kangmingtay** [comment] 2021-06-29 01:33
Hey @heauton, which endpoint were you calling that led to this?

**Comment by emschwartz** [comment] 2021-06-29 21:52
I'm also seeing this issue.

I have `http://localhost:3000` as one of 3 additional URLs. When I call `supabase.auth.signIn` with `redirectTo: 'http://localhost:3000/some/path'`, the link that is emailed to the user contains `redirect_to=https://my-site-url.com`.

**Comment by JSsantana** [comment] 2021-06-30 01:58
I'm having the same issue.

**Comment by awalias** [comment] 2021-06-30 08:47
@heauton are you able to reproduce this? It may have been something related to our internal infrastructure if there was some delay in the setting of the values

@emschwartz this seems like the correct behaviour - the additional URLs need to be *exact* matches (including scheme, path), so you would need to add `http://localhost:3000/some/path` to be able to redirect to this URI

note: the purpose of additional URLs was initially for mobile deep links which may not conform to the standard `scheme://sub.domain.tld` pattern hence why we can not match the host securely with wildcard paths etc.

**Comment by emschwartz** [comment] 2021-06-30 13:25
@awalias I didn't have that exact path in the additional URLs. Will it let through dynamic query strings? Or, is there a way I could change the additional URLs programmatically (ideally with a DB trigger but alternatively with an API call)? I need people to be able to login to a specific page whose path is dynamically generated.

**Comment by awalias** [comment] 2021-07-01 02:22
sure! I think you already saw the related issue here: https://github.com/supabase/gotrue/issues/99

I think it should support your use case

for the current field (additional uris) it's difficult for us to parse the strings securely since mobile deep links can take any form (sometimes reverse URLs for example)

**Comment by conradlin** [comment] 2021-07-02 10:20
I'm having the same issue. What is the best way to handle additional urls for development use cases?

**Comment by kangmingtay** [comment] 2021-07-29 05:42
We've fixed this issue already and i'm gonna close this issue for now. Please feel free to reopen it if you're still experiencing these issues thanks!

**Closed by kangmingtay** 2021-07-29 05:42 UTC
